BASE_URL = "https://www.goodreads.com/"
CSV_PATH = r"csv/books.csv"
JSON_PATH = r"json/books.json"
QUOTE_PATH = r"txt/quotes.txt"
CHROME_AGENTS_URL = "https://raw.githubusercontent.com/tamimibrahim17/List-of-user-agents/master/Chrome.txt"
